<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-V4K2H45Q" name="RetryAnalyzer Retry" tests="7" failures="1" timestamp="29 Apr 2019 15:47:53 GMT" time="0.087" errors="0">
  <testcase name="test1" time="0.019" classname="TestNGRetryer.TestrRetry"/>
  <testcase name="test2" time="0.003" classname="TestNGRetryer.TestrRetry">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="TestNGRetryer.TestrRetry">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="TestNGRetryer.TestrRetry">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="TestNGRetryer.TestrRetry">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="TestNGRetryer.TestrRetry">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.004" classname="TestNGRetryer.TestrRetry">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at TestNGRetryer.TestrRetry.test2(TestrRetry.java:17)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- RetryAnalyzer Retry -->
